version: '3.8'

services:
  script-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: script-server:latest
    container_name: script-server-dev
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=dev
    volumes:
      # 可选：挂载日志目录
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/script/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # 可选：添加监控服务
  # monitoring:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  default:
    name: script-server-network
